### ISSUE TITLE
Generate register block accessors from SVD files

### ISSUE THREAD

**Issue by japaric** [japaric/cu#36]
Ideally: the output (Rust structs) of the generator should be "fairly" customizable and the generator should work on stable Rust. This means that the "generator" could simply be a SVD parser plus utility functions to generate Rust structs.

@dzamlo is experimenting with this idea in [this repository](https://github.com/dzamlo/svd). **Disclaimer**: I haven't checked the repository in detail, but I'll leave some comments after I do.

**Comment by dzamlo** [comment]
I'd like to add that the SVD could also help with generating the vector table: the interrupts of the peripherals are listed in the SVD (with a name, a description and the interrupt number)

**Comment by japaric** [comment]
There's an SVD parser here: https://github.com/japaric/svd

**Comment by japaric** [comment]
[svd2rust](https://crates.io/crates/svd2rust) is a thing now.
